version: "3.8"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb+srv://sanndph32936:sandapchai12@cluster0.cstvl.mongodb.net/Learning?retryWrites=true&w=majority&appName=Cluster0"
 
    restart: always

  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
